name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup .NET 8 SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build solution
      - name: Build solution
        run: dotnet build MiniPricingPlatform.sln --configuration Release

      # 5️⃣ Run tests
      - name: Run tests
        run: dotnet test MiniPricingPlatform.sln --configuration Release --no-restore --verbosity normal

      # 6️⃣ Lint using dotnet format
      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format
        run: dotnet format MiniPricingPlatform.sln

      - name: Build Docker image
        run: docker build -t mini-pricing-api .

      - name: Save Docker image as tar
        run: docker save mini-pricing-api:latest -o mini-pricing-api.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: mini-pricing-api-image
          path: mini-pricing-api.tar